# Generated by Django 4.2.26 on 2025-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDemo_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_demo_video', models.FileField(upload_to='student_demo_video/', verbose_name='Demo Video')),
            ],
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_sheet', models.FileField(upload_to='student_markSheet/', verbose_name='MarkSheet')),
            ],
        ),
        migrations.CreateModel(
            name='StrongSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='Strong Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAsTeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=200, verbose_name='Achievement')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_picture/', verbose_name='Profile Picture')),
                ('demo_video', models.ManyToManyField(related_name='student_teach_reg', to='student_teach_register_app.livedemo_student')),
                ('mark_sheet', models.ManyToManyField(related_name='student_teach_reg', to='student_teach_register_app.marksheet')),
                ('strong_subject', models.ManyToManyField(related_name='student_teach_reg', to='student_teach_register_app.strongsubject')),
            ],
        ),
    ]
