# Generated by Django 4.2.26 on 2025-12-18 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='student_register_app.city')),
            ],
            options={
                'ordering': ['college_name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='User Name')),
                ('occupation', models.TextField(max_length=100, verbose_name='Occupation')),
                ('phone_number', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('email_id', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Select', max_length=10, null=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_semester', models.CharField(max_length=50, verbose_name='College Semester')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject you want learn')),
                ('selected_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration', to='student_register_app.city')),
                ('selected_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration', to='student_register_app.college')),
                ('selected_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration', to='student_register_app.district')),
                ('selected_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration', to='student_register_app.state')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='student_register_app.state'),
        ),
        migrations.AddField(
            model_name='college',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='student_register_app.district'),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='student_register_app.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='student_register_app.district'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'district_name')},
        ),
        migrations.AlterUniqueTogether(
            name='college',
            unique_together={('city', 'college_name')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('district', 'city_name')},
        ),
    ]
