# Generated by Django 4.2.26 on 2025-12-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_register_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='certifications/')),
                ('certification_name', models.TextField(max_length=50, verbose_name='Certification Name')),
            ],
        ),
        migrations.CreateModel(
            name='LiveDemo_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_demo_video', models.FileField(upload_to='live_demos_teacher/')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_to_teach', models.TextField(max_length=50, verbose_name='Subject To Teach')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTeachReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=150, verbose_name='Experience')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='prof_teach_profile/', verbose_name='Profile Picture')),
                ('achievement', models.CharField(max_length=200, verbose_name='Achievement')),
                ('certification', models.ManyToManyField(related_name='professional_teacher', to='prof_teacher_register_app.certification')),
                ('live_demo', models.ManyToManyField(related_name='professional_teacher', to='prof_teacher_register_app.livedemo_teacher')),
                ('selected_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_teacher', to='student_register_app.city')),
                ('selected_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_teacher', to='student_register_app.college')),
                ('selected_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_teacher', to='student_register_app.district')),
                ('selected_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_teacher', to='student_register_app.state')),
                ('subject_to_teach', models.ManyToManyField(related_name='professional_teacher', to='prof_teacher_register_app.teachingsubject')),
            ],
        ),
    ]
